# kubernetes/reporting-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
  namespace: splitwise-dev
  labels:
    app: reporting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
      - name: reporting-service
        image: your_docker_username/reporting-service:latest # REPLACE WITH YOUR IMAGE
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_DB_URL
          value: "mongodb://$(MONGO_ROOT_USERNAME):$(MONGO_ROOT_PASSWORD)@mongodb.splitwise-dev.svc.cluster.local:27017/$(REPORTING_DB_NAME)?authSource=admin"
        - name: JWT_SECRET_KEY # If it exposes any authenticated endpoints
          valueFrom:
            secretKeyRef:
              name: splitwise-secrets
              key: JWT_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: JWT_ALGORITHM
        - name: REPORTING_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: REPORTING_DB_NAME
        # RabbitMQ (if it consumes messages for reporting)
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: splitwise-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: splitwise-secrets
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_QUEUE_EXPENSE_CREATED # If it consumes this queue
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: RABBITMQ_QUEUE_EXPENSE_CREATED
        - name: RABBITMQ_QUEUE_PAYMENT_PROCESSED # If it consumes this queue
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: RABBITMQ_QUEUE_PAYMENT_PROCESSED
        - name: RABBITMQ_QUEUE_REPORT_REQUESTED # If it consumes this queue
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: RABBITMQ_QUEUE_REPORT_REQUESTED
        readinessProbe:
          httpGet:
            path: /reports/health # Assuming /reports/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /reports/health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20