# kubernetes/group-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
  namespace: splitwise-dev
  labels:
    app: group-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-service
  template:
    metadata:
      labels:
        app: group-service
    spec:
      containers:
      - name: group-service
        image: your_docker_username/group-service:latest # REPLACE WITH YOUR IMAGE
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_DB_URL
          value: "mongodb://$(MONGO_ROOT_USERNAME):$(MONGO_ROOT_PASSWORD)@mongodb.splitwise-dev.svc.cluster.local:27017/$(GROUP_DB_NAME)?authSource=admin"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: splitwise-secrets
              key: JWT_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: JWT_ALGORITHM
        - name: GROUP_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: GROUP_DB_NAME
        readinessProbe:
          httpGet:
            path: /groups/health # Assuming /groups/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /groups/health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20