# kubernetes/payment-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: splitwise-dev
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: your_docker_username/payment-service:latest # REPLACE WITH YOUR IMAGE
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_DB_URL
          value: "mongodb://$(MONGO_ROOT_USERNAME):$(MONGO_ROOT_PASSWORD)@mongodb.splitwise-dev.svc.cluster.local:27017/$(PAYMENT_DB_NAME)?authSource=admin"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: splitwise-secrets
              key: JWT_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: JWT_ALGORITHM
        - name: PAYMENT_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: PAYMENT_DB_NAME
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: splitwise-secrets
              key: STRIPE_SECRET_KEY
        # RabbitMQ (if it consumes/produces messages)
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: splitwise-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: splitwise-secrets
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_QUEUE_PAYMENT_PROCESSED
          valueFrom:
            configMapKeyRef:
              name: splitwise-config
              key: RABBITMQ_QUEUE_PAYMENT_PROCESSED
        readinessProbe:
          httpGet:
            path: /payments/health # Assuming /payments/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /payments/health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20