# kubernetes/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: splitwise-secrets
  namespace: splitwise-dev
type: Opaque
data:
  # MongoDB Credentials (from your docker-compose.yml or your chosen values)
  # echo -n "your_mongo_root_username" | base64
  MONGO_ROOT_USERNAME: <base64-encoded-mongo-root-username>
  # echo -n "your_mongo_root_password" | base64
  MONGO_ROOT_PASSWORD: <base64-encoded-mongo-root-password>

  # JWT Secret Key (MUST be the same across auth and all services validating tokens)
  # echo -n "Vf91jZ@r5u^FqK!3xNmzT#L6yW8eZb9Q\$C1pO7Rg" | base64
  JWT_SECRET_KEY: VmY5MWpaQHI1dSVGcUshM3hObXpUI0w2eVc4ZVpiOVFTQzFwTzdSZw==

  # RabbitMQ Credentials (from your docker-compose.yml or your chosen values)
  # echo -n "guest" | base64
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  # echo -n "guest" | base64
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=

  # Stripe API Key (for payment_service)
  # echo -n "sk_test_..." | base64
  STRIPE_SECRET_KEY: <base64-encoded-stripe-secret-key>

  # Gemini AI API Key (for ai_splitter_service)
  # echo -n "your_gemini_api_key" | base64
  GEMINI_API_KEY: <base64-encoded-gemini-api-key>